server:
  port:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/url?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
